### ISSUE TITLE
Bug: Save button on cabin setting page not working 

### ISSUE THREAD

**Issue by einmid** [rubberdok/indok-web#1252] opened 2022-11-08 19:23 UTC
In cabin settings page, the "Lagre"-button for bookable dates is not working.
Attached is screenshot of button and screenshot of console with error messages.

![Save button](https://user-images.githubusercontent.com/89466996/200656239-d34b9d39-8e12-454b-b6dd-125d20f1eaa3.png)
![Console errors](https://user-images.githubusercontent.com/89466996/200656271-74b17e40-b4ff-40f1-8adf-232d5bab1353.png)

**Comment by larwaa** [comment] 2023-05-25 17:30
Duplicate of #1648

**Closed by larwaa** 2023-05-25 17:30 UTC
